pub const MAX_INPUT_BUFFER_SIZE: usize = 6;
pub const BOARD_POSITION_X: i32 = 3;
pub const BOARD_POSITION_Y: i32 = 1;

pub const THEME_BOARD_HINT: u32 = 1;
pub const THEME_BOARD_TEXT_WHITE: u32 = 2;
pub const THEME_BOARD_TEXT_BLACK: u32 = 3;

pub const THEME_BOARD_CELL_WHITE_WHITE_PIECE: u32 = 4;
pub const THEME_BOARD_CELL_WHITE_BLACK_PIECE: u32 = 5;
pub const THEME_BOARD_CELL_BLACK_WHITE_PIECE: u32 = 6;
pub const THEME_BOARD_CELL_BLACK_BLACK_PIECE: u32 = 7;
